In [3]:
import pandas as pd 
import numpy as  NP
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv("IMDB-Movie-Data-clean.csv")

In [5]:
df.shape

(1000, 14)

In [7]:
df.head()

,Unnamed: 0.1,Unnamed: 0,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,0,0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,1,1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,2,2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,3,3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,4,4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [8]:
df.describe()

,Unnamed: 0.1,Unnamed: 0,Rank,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,1000.000000,1000.000000
mean,499.500000,499.500000,500.500000,2012.783000,113.172000,6.723200,1.698083e+05,72.337960,55.914000
std,288.819436,288.819436,288.819436,3.205962,18.810908,0.945429,1.887626e+05,100.320314,20.366379
min,0.000000,0.000000,1.000000,2006.000000,66.000000,1.900000,6.100000e+01,0.000000,11.000000
25%,249.750000,249.750000,250.750000,2010.000000,100.000000,6.200000,3.630900e+04,3.352500,43.000000
50%,499.500000,499.500000,500.500000,2014.000000,111.000000,6.800000,1.107990e+05,37.145000,58.000000
75%,749.250000,749.250000,750.250000,2016.000000,123.000000,7.400000,2.399098e+05,99.177500,71.000000
max,999.000000,999.000000,1000.000000,2016.000000,191.000000,9.000000,1.791916e+06,936.630000,100.000000

In [ ]:
    df.drop_column["Unnamed:0.1"

AttributeError: 'DataFrame' object has no attribute 'drop_column'